# Example configuration for blockwheel_kv benchmark.

# blockwheel_kv key-value database related parameters
[blockwheel_kv]
# blockwheel kv storage n-tree block size
tree_block_size = 256
# butcher task restart timeout (seconds) for blockwheel kv storage
butcher_task_restart_sec = 1
# manager task restart timeout (seconds) for blockwheel kv storage
manager_task_restart_sec = 1
# search tree task restart timeout (seconds) for blockwheel kv storage
search_tree_task_restart_sec = 1
# maximum number of simultaneously running blocks removing tasks for blockwheel kv storage
search_tree_remove_tasks_limit = 64
# mpsc channel send buffer before backpressure for iterators in blockwheel kv storage
search_tree_iter_send_buffer = 4

# storage areas manager related parameters
[blockwheel_wheels]
# main task restart timeout (seconds) for blockwheel kv wheels task
task_restart_sec = 1

# actual storage areas list related parameters
[[blockwheel_wheels.fss]]
# backend file for blockwheel fs
wheel_filename = "blockwheel_kv.blocks"
# initial size for backend file in case of creating new for blockwheel fs
# init_wheel_size_bytes = 1073741824
init_wheel_size_bytes = 2147483648
# main wheel task restart timeout (in seconds) for blockwheel fs
wheel_task_restart_sec = 4
# tasks pool limit for main wheel task in blockwheel fs
wheel_task_tasks_limit = 64
# work block size for fs ops in blockwheel fs
work_block_size_bytes = 8388608
# LRU cache maximum size (in bytes) in blockwheel fs
lru_cache_size_bytes = 8388608
# maximum number of simultaneously running defragmentation tasks in blockwheel fs
defrag_parallel_tasks_limit = 16

# sled key-value database related parameters
[sled]
# the path of the database
directory = "database.sled"
# maximum size in bytes for the system page cache
cache_capacity = 16777216 # set lower to force disk access
# specify whether the system should run in \"small\" or \"fast\" mode
mode = "fast"
# print a performance profile when the Config is dropped
print_profile_on_drop = true

# bench related parameter
[bench]
# maximum number of parallel kv access tasks
active_tasks = 3072
# total number of actions with kv database
# actions = 131072
actions = 1048576
# maximum key size in bytes
key_size_bytes = 32
# maximum value size in bytes
value_size_bytes = 4096
# db insert operation timeout (in seconds)
timeout_insert_secs = 30
# db lookup operation timeout (in seconds)
timeout_lookup_secs = 60
# db lookup range operation timeout (in seconds)
timeout_lookup_range_secs = 60
# db remove operation timeout (in seconds)
timeout_remove_secs = 30
# db flush operation timeout (in seconds)
timeout_flush_secs = 360
